import { useContext } from 'react'
import FilterContext from 'context/FilterContext'
import Head from 'next/head'
import Layout from 'components/Layout'

export default function Home() {

  const {hola} = useContext(FilterContext)
  
  return (
    <>
      <Head>
        <title>Open Data FIS Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex-grow">
        <article className="flex flex-col justify-center items-center w-4/5 h-full px-4 mx-auto">
          <h1 className="text-2xl text-black text-center font-semibold mb-2">
            Repositorio Institucional Universidad Distrital - Proyecto FIS
          </h1>
          <p className="text-base text-black text-center font-thin mb-2">
            El Repositorio Institucional de la Universidad Francisco José de Caldas RIUD es una herramienta donde 
            se depositan los objetos digitales que corresponden a la producción intelectual de la Universidad para proteger, 
            preservar, y difundir.
          </p>
          <p className="text-base text-black text-center font-thin">
            Puedes ver 
          </p>
        </article>
      </section>



    </>
  )
}

Home.getLayout = (page) => {
  return (
    <Layout>
      {page}
    </Layout>
  )
}
